version: '3.8'

services:
  sensor-adapter:
    build: .
    ports:
      - "8002:8002"       # HTTP API
      - "9999:9999"       # TCP сервер
    environment:
      DATABASE_URL: postgresql+asyncpg://sensors_user:sensors_pass@db:5432/sensors_db
      ENABLE_TCP_SERVER: "true"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sensors_db
      POSTGRES_USER: sensors_user
      POSTGRES_PASSWORD: sensors_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
