version: '3.8'

services:
  sensor-adapter:
    build: .
    ports:
      - "8002:${APP_PORT}"       # HTTP API
      - "9999:${APP_TCP_PORT}"       # TCP сервер
    volumes:
      - ./app:/code/app
      - ./tests:/code/tests
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sensors_db
      POSTGRES_USER: sensors_user
      POSTGRES_PASSWORD: sensors_pass
    volumes:
      - postgres_data_sensors:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  postgres_data_sensors:
